### ISSUE TITLE
Unused variables referenced in install step

### ISSUE THREAD

**Issue by randombit** [bkircher/botan2-fedora#1]
The install step does this

```
make install \
     DESTDIR=%{buildroot} \
     INSTALL_CMD_EXEC="install -p -m 755" \
     INSTALL_CMD_DATA="install -p -m 644"
```

But as of 2.4.0 the INSTALL_ variables are not used anymore. Instead a Python script (src/scripts/install.py) handles the install step, this allows consistent operation between Windows and Unix systems. Probably these variable settings can just be removed now.

**Comment by bkircher** [comment]
Thanks for the pointer!

**Comment by bkircher** [comment]
Done in fb1c818
